<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithCustomStartCell;
use Maatwebsite\Excel\Concerns\WithStyles;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class ProductExport implements FromArray, WithCustomStartCell, WithStyles
{
    protected $data;
    protected $metaInfo;
    protected $headers;

    // Accept products data, meta info, and headers from controller
    public function __construct(array $data, array $metaInfo, array $headers)
    {
        $this->data = $data;
        $this->metaInfo = $metaInfo;
        $this->headers = $headers;
    }

    // Prepare export array with meta info, headers, and product rows
    public function array(): array
    {
        $exportData = [
            ["Date Range  :  " . ($this->metaInfo['date_range'] ?? '')],
            ["Generated By :  " . ($this->metaInfo['generated_by'] ?? 'System')],
            [""], // Blank line separator
        ];

        // Add header row
        $exportData[] = $this->headers;

        // Append product data
        $exportData = array_merge($exportData, $this->data);

        return $exportData;
    }

    // Start export from cell A2 (adjust as needed)
    public function startCell(): string
    {
        return 'A2';
    }

    // Apply styles to header/meta cells
    public function styles(Worksheet $sheet)
    {
        $lastHeaderRow = count($this->metaInfo) + 3; // Approximate header/meta rows count

        $sheet->getStyle('A1:' . $sheet->getHighestColumn() . $lastHeaderRow)->applyFromArray([
            'font' => [
                'bold' => true,
            ],
            'alignment' => [
                'vertical' => \PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER,
            ],
        ]);

        // Merge meta info rows for cleaner look
        $sheet->mergeCells('A1:E1');
        $sheet->mergeCells('A2:E2');
        $sheet->mergeCells('A3:E3');
    }
}