<?php $__env->startSection('title', isset($device_registration_id) ? 'Device - Edit' : 'Device - Create'); ?>

<?php $__env->startSection('content'); ?>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header border-bottom">
                    <h5 class="card-title"><?php echo e(isset($device_registration_id) ? 'Update Device' : 'Register Device'); ?></h5>
                </div>
                <div class="card-body">
                    <form class="needs-validation" novalidate id="deviceRegForm">
                        <?php echo e(csrf_field()); ?>

                        <div class="row g-3">
                            <div class="col-md-6">
                                <label class="form-label">Device ID</label>
                                <input type="text" name="device_id" id="device_id" class="form-control"
                                    value="<?php echo e($info->device_id ?? ''); ?>" required>
                                <div class="invalid-feedback">Please enter device id</div>
                            </div>

                            <div class="col-md-6">
                                <label class="form-label">Serial Number</label>
                                <input type="text" name="serial_number" class="form-control"
                                    value="<?php echo e($info->serial_number ?? ''); ?>">
                            </div>

                            <div class="col-md-6">
                                <label class="form-label">License Key</label>
                                <input type="text" class="form-control"
                                    value="<?php echo e($info->license_key ?? 'Will be generated on save'); ?>" disabled>
                                <small class="text-muted">License key is generated by backend and won't change after
                                    creation</small>
                            </div>

                            <div class="col-md-3">
                                <label class="form-label">Start Date</label>
                                <input type="date" name="start_date" class="form-control"
                                    value="<?php echo e(isset($info->start_date) ? date('Y-m-d', strtotime($info->start_date)) : ''); ?>"
                                    required>
                            </div>

                            <div class="col-md-3">
                                <label class="form-label">End Date</label>
                                <input type="date" name="end_date" class="form-control"
                                    value="<?php echo e(isset($info->end_date) ? date('Y-m-d', strtotime($info->end_date)) : ''); ?>"
                                    required>
                            </div>


                            <div class="col-md-3">
                                <label class="form-label d-block">Status</label>
                                <select name="status" class="form-select">
                                    <option value="ACTIVE"
                                        <?php echo e(isset($info) && $info->status == 'ACTIVE' ? 'selected' : ''); ?>>ACTIVE</option>
                                    <option value="INACTIVE"
                                        <?php echo e(isset($info) && $info->status == 'INACTIVE' ? 'selected' : ''); ?>>INACTIVE
                                    </option>
                                    <option value="EXPIRE"
                                        <?php echo e(isset($info) && $info->status == 'EXPIRE' ? 'selected' : ''); ?>>EXPIRE</option>
                                </select>
                            </div>


                            
                            <div class="col-md-3">
                                <label class="form-label">App Update Required</label>
                                <select name="is_update_required" class="form-select">
                                    <option value="1"
                                        <?php echo e(isset($info) && $info->is_update_required == 1 ? 'selected' : ''); ?>>YES</option>
                                    <option value="0"
                                        <?php echo e(isset($info) && $info->is_update_required == 0 ? 'selected' : ''); ?>>NO
                                    </option>

                                </select>
                            </div>
                            <div class="col-md-3">
                                <label class="form-label">Current App Version Code</label>
                                <input type="text" name="latest_version_code" class="form-control"
                                    value="<?php echo e($info->latest_version_code ?? 0); ?>" disabled>
                            </div>
                            

                        </div>

                        <div class="mt-4 text-end">
                            <button type="button" onclick="history.back()" class="btn btn-secondary me-2">Back</button>
                            <button type="submit" class="btn btn-primary" id="submitBtn">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
<?php $__env->stopSection(); ?>

<?php $__env->startSection('page-script'); ?>
    <script>
        $(document).ready(function() {
            var form = $('#deviceRegForm');
            form.on('submit', function(e) {
                e.preventDefault();

                if (!form[0].checkValidity()) {
                    form.addClass('was-validated');
                    return;
                }

                var submitBtn = $('#submitBtn').prop('disabled', true).text('Submitting...');
                var id = "<?php echo e($device_registration_id ?? ''); ?>";
                var url = "<?php echo e(route('device_registration.save')); ?>" + (id ? '/' + id : '');
                var data = form.serialize();

                $.ajax({
                    url: url,
                    method: 'POST',
                    data: data,
                    success: function(resp) {
                        if (resp.success) {
                            toastr.success(resp.message || 'Saved successfully');
                            window.location.href = "<?php echo e(route('device_registration')); ?>";
                        } else {
                            toastr.error(resp.message || 'Save failed');
                            submitBtn.prop('disabled', false).text('Submit');
                        }
                    },
                    error: function(xhr) {
                        var errors = xhr.responseJSON?.errors;
                        if (errors) {
                            toastr.error(errors.join('<br>'));
                        } else {
                            toastr.error(xhr.responseJSON?.message || 'An error occurred');
                        }
                        submitBtn.prop('disabled', false).text('Submit');
                    }
                });
            });
        });
    </script>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts/contentNavbarLayout', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH /var/www/html/gallamattressapp/resources/views/content/device_registration/create.blade.php ENDPATH**/ ?>