@extends('layouts/contentNavbarLayout')

@section('title', 'Device Registration - List')
@section('page-style')
    <link rel="stylesheet" href="{{ asset('assets/css/datatables.bootstrap5.css') }}">
    <style>
        table.dataTable tbody tr td {
            vertical-align: middle;
        }
    </style>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card p-3">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h5 class="mb-0">Device Registrations</h5>
                        <small class="text-muted">Manage device licenses</small>
                    </div>
                    <a href="{{ route('device_registration.create') }}" class="btn btn-primary">
                        <i class="bx bx-plus"></i> Add Device
                    </a>
                </div>

                <div class="card-datatable table-responsive pt-0">
                    <!-- NO THEAD / TBODY — SAME AS PRODUCTS PAGE -->
                    <table class="datatables-basic table table-bordered table-striped" id="DataTables2025"></table>
                </div>
            </div>
        </div>
    </div>

    <!-- View Modal -->
    <div class="modal fade" id="viewRowDetails" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-md">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="row-title">Device</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <dl class="row">
                        <dt class="col-sm-4">Device ID</dt>
                        <dd class="col-sm-8" id="device_id">-</dd>

                        <dt class="col-sm-4">Serial</dt>
                        <dd class="col-sm-8" id="serial_number">-</dd>

                        <dt class="col-sm-4">License</dt>
                        <dd class="col-sm-8" id="license_key">-</dd>

                        <dt class="col-sm-4">Start</dt>
                        <dd class="col-sm-8" id="start_date">-</dd>

                        <dt class="col-sm-4">End</dt>
                        <dd class="col-sm-8" id="end_date">-</dd>

                        <dt class="col-sm-4">Status</dt>
                        <dd class="col-sm-8" id="status">-</dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
@endsection


@section('page-script')
    @include('content.partial.datatable')

    <script>
        $(document).ready(function() {

            // Table headers coming from controller (auto-generated by TableHelper)
            var tableHeaders = {!! $table_headers !!};

            // Setup options (same format as Products List)
            const options = {
                url: "{{ route('device_registration.list') }}",
                createUrl: "{{ route('device_registration.create') }}",
                displayLength: 20,
                is_delete: 0,
                delete_url: "{{ route('device_registration.delete') }}",
                manuall_create: false,
                is_export: 0,
                is_export2: 0,
                is_import: 0,
                createPermissions: 1,
            };

            // Initialize the DataTable using your universal function
            getDataTableS(options, {}, tableHeaders);

            // View button handler
            $(document).on('click', '.btn-view-row', function(e) {
                e.preventDefault();
                const url = $(this).data('url') || $(this).attr('href');
                if (url) viewRowDetails(url);
            });

        });


        // AJAX View handler — same as products
        window.viewRowDetails = function(url) {
            $.ajax(url, {
                    dataType: 'json'
                })
                .done(function(resp) {
                    if (resp.data) {
                        const d = resp.data;

                        $('#row-title').text(d.device_id ?? '-');
                        $('#device_id').text(d.device_id ?? '-');
                        $('#serial_number').text(d.serial_number ?? '-');
                        $('#license_key').text(d.license_key ?? '-');
                        $('#start_date').text(d.start_date ?? '-');
                        $('#end_date').text(d.end_date ?? '-');

                        let s = d.status;
                        if (s === 'ACTIVE') s = '<span class="badge bg-label-success">ACTIVE</span>';
                        else if (s === 'INACTIVE') s = '<span class="badge bg-label-secondary">INACTIVE</span>';
                        else s = '<span class="badge bg-label-danger">EXPIRE</span>';

                        $('#status').html(s);

                        new bootstrap.Modal(document.getElementById('viewRowDetails')).show();
                    } else {
                        toastr.error("Failed to fetch row details.");
                    }
                })
                .fail(function() {
                    toastr.error("Error fetching row details.");
                });
        };


        // Server delete handler using unified delete system
        function onDelete(row_id = '') {
            delete_url = "{{ route('device_registration.delete') }}";

            if (!row_id || row_id == 0) {
                alert('Delete Failed Please Contact Support.');
                return;
            }

            if (!confirm('Are you sure you want to delete this item ? This action cannot be undone.')) {
                return;
            }

            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                url: delete_url,
                method: 'POST',
                data: {
                    id: row_id
                },
                success: function(response) {
                    if (response.success) {
                        toastr.success(response.message || ('Deleted successfully'));
                        setTimeout(() => {
                            window.location.reload();
                        }, 1000);
                    } else {
                        toastr.error(response.message || 'Delete failed');
                    }
                },
                error: function(xhr, status, error) {
                    var msg = xhr.responseJSON?.message || error;
                    toastr.error("Error: " + msg);
                }
            });
        }
    </script>

@endsection
